#YAML template to configure the microservice to be uploaded into AWS cloudformation lambda
#Microservices endpoints are configured for each lambda function
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Reto 4

  SAM Template for Radionet users management service

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active    
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: app.get_users
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
  GetUserFuntion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: app.test_fun
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user
            Method: get
  InsertUserFuntion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: app.insert_user
      Runtime: python3.8
      Architectures:
      - x86_64
      Events:
        InsertUser:
          Type: Api
          Properties:
            Path: /insert
            Method: get

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetUsersFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt GetUsersFunction.Arn
  GetUsersFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt GetUsersFunction.Arn
